// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostDatabaseData, PostDatabaseResponse, PostDatabaseError, GetGreetingData, GetGreetingResponse, GetGreetingError } from './types.gen';

export const client = createClient(createConfig());

/**
 * Post a database
 */
export const postDatabase = <ThrowOnError extends boolean = false>(options: Options<PostDatabaseData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostDatabaseResponse, PostDatabaseError, ThrowOnError>({
        url: '/database',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get a greeting
 * Get a greeting for a person by name.
 */
export const getGreeting = <ThrowOnError extends boolean = false>(options: Options<GetGreetingData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGreetingResponse, GetGreetingError, ThrowOnError>({
        url: '/greeting/{name}',
        ...options
    });
};