// This file is auto-generated by @hey-api/openapi-ts

export type DatabaseCreationRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Name of the database
     */
    name: string;
    /**
     * Tier of the database (e.g., standard, premium)
     */
    tier: string;
    /**
     * Type of the database (e.g., postgresql, mysql)
     */
    type: string;
};

export type DatabaseCreationResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Unique identifier for the database
     */
    id: string;
    /**
     * Name of the database
     */
    name: string;
    /**
     * Tier of the database
     */
    tier: string;
    /**
     * Type of the database
     */
    type: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GreetingOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Greeting message
     */
    message: string;
};

export type PostDatabaseData = {
    body: DatabaseCreationRequestBody;
    path?: never;
    query?: never;
    url: '/database';
};

export type PostDatabaseErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostDatabaseError = PostDatabaseErrors[keyof PostDatabaseErrors];

export type PostDatabaseResponses = {
    /**
     * Created
     */
    201: DatabaseCreationResponseBody;
};

export type PostDatabaseResponse = PostDatabaseResponses[keyof PostDatabaseResponses];

export type GetGreetingData = {
    body?: never;
    path: {
        /**
         * Name to greet
         */
        name: string;
    };
    query?: never;
    url: '/greeting/{name}';
};

export type GetGreetingErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetGreetingError = GetGreetingErrors[keyof GetGreetingErrors];

export type GetGreetingResponses = {
    /**
     * OK
     */
    200: GreetingOutputBody;
};

export type GetGreetingResponse = GetGreetingResponses[keyof GetGreetingResponses];